/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gdit.capture.services;

import com.gdit.capture.entity.Capture;
import com.gdit.capture.entity.CaptureHome;
import com.gdit.capture.entity.Disk;
import com.gdit.capture.entity.DiskHome;
import com.gdit.capture.entity.Rep;
import java.io.File;
import java.util.List;
import net.sourceforge.tess4j.Tesseract;
import org.tempuri.CompressToTiff;

/**
 *
 * @author Administrator
 */
public class BarcodeDLG extends javax.swing.JDialog {

    /**
     * Creates new form BarcodeDLG
     */
    private Rep rep;

    public BarcodeDLG(java.awt.Frame parent, boolean modal, Rep rep) {
        super(parent, modal);
        this.rep = rep;
       
        initComponents();
         repName.setText(rep.getName());
        setVisible(true);
        seperate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        repName = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        repName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        repName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        output.setColumns(20);
        output.setRows(5);
        jScrollPane2.setViewportView(output);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(repName, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(repName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
    }

    private void seperate() {
        try {

//            
            CaptureHome dao = new CaptureHome();
//            ReadBarcode reader = new ReadBarcode();
            

            while (true) {
                List<Capture> batches = dao.getUnBarcoded(rep);
                for (Capture batch : batches) {

                     output.append("\n "+batch.getId());
                    System.out.println( batch.getId());
                    List<Capture> pages = dao.getBatchUnDeletedPages(batch);
                    batch.setBarcoded(true);
                    dao.attachDirty(batch);
                    if (pages.isEmpty() || batch.getComputer() == null || batch.getDisk() == null) {
                        continue;
                    }
                    Capture first = pages.get(0);
                    File imgFile = new File(batch.getDisk().getPath() + "/scan/"
                            + batch.getId() + "//" + first.getPath());
                    File viewFile = new File(batch.getDisk().getViewPath() + "/view/"
                            + batch.getId() + "//" + first.getPath());
                    if (viewFile.exists()) {
                        String barcode = "";
//                        barcode = reader.scanBarcode(imgFile);
//                        if (!barcode.equals("")) {
//                            Capture doc = (Capture) batch.getCaptures().toArray()[0];
//                            doc.setName(barcode.trim());
//                            doc.setBarcode(barcode.trim());
//                            dao.attachDirty(doc);
//                            continue;
//                        }
                        String result = Tesseract.getInstance().doOCR(imgFile);
                        String[] splits = result.split("\\n");
                        if (splits[0].length() > 14) {
                            continue;
                        }
                        barcode = splits[0].replaceAll("\\s", "");
//                        for (String split : splits) {
//                            String str = split.trim();
//                            if (isLong(str)) {
//                                barcode = str;
//                                break;
//                            }
//                        }


                        if (isLong(barcode)) {
                            Capture doc = (Capture) batch.getCaptures().toArray()[0];
                            doc.setName(barcode.trim());
                            doc.setBarcode(barcode.trim());
                            dao.attachDirty(doc);
                            output.append("\n"+ batch.getId() + "      " + barcode);
//                       output.append("\n"+ batch.getId() + "      " + barcode);
                        }

                    }
//                      else {
//                        File from = new File("\\\\" + batch.getComputer().getName() + "\\141\\" + batch.getId());
//                        if (!from.exists()) {
//                            from = new File("G:/" + batch.getComputer().getName() + "\\20042013\\" + batch.getId());
//                        }
//                        File to = new File(batch.getDisk().getPath() + "\\" + batch.getId());
//                        File tof = new File(batch.getDisk().getViewPath() + "\\" + batch.getId());
//                        if (!to.exists() || to.list() == null || to.list().length <= 1) {
//                            org.apache.commons.io.FileUtils.copyDirectory(from, to);
//                            CompressToTiff service = new CompressToTiff();
//                            service.getCompressToTiffSoap().compressFolderFullPath(disk.getPath() + "/" + batch.getId(),
//                                    disk.getViewPath() + "/" + batch.getId());
//
//                            String result = Tesseract.getInstance().doOCR(imgFile);
//                            String[] splits = result.split("\\n");
//                            if (splits[0].length() > 14) {
//                                continue;
//                            }
//                            String barcode = splits[0].replaceAll("\\s", "");
//
//                            if (isLong(barcode)) {
//                                Capture doc = (Capture) batch.getCaptures().toArray()[0];
//                                doc.setName(barcode.trim());
//                                doc.setBarcode(barcode.trim());
//                                dao.attachDirty(doc);
//                                output.append("\n"+batch.getId() + "      " + barcode);
////                             output.append("\n"+ batch.getId() + "      " + barcode);
//                            }
//                        } else if (!tof.exists() || tof.list() == null || tof.list().length <= 1) {
//                            CompressToTiff service = new CompressToTiff();
//                            service.getCompressToTiffSoap().compressFolderFullPath(disk.getPath() + "/" + batch.getId(),
//                                    disk.getViewPath() + "/" + batch.getId());
//
//                            String result = Tesseract.getInstance().doOCR(imgFile);
//                            String[] splits = result.split("\\n");
//                            if (splits[0].length() > 12) {
//                                continue;
//                            }
//                            String barcode = splits[0].replaceAll("\\s", "");
//
//                            if (isLong(barcode)) {
//                                Capture doc = (Capture) batch.getCaptures().toArray()[0];
//                                doc.setName(barcode.trim());
//                                doc.setBarcode(barcode.trim());
//                                dao.attachDirty(doc);
//                                output.append("\n"+batch.getId() + "      " + barcode);
////                             output.append("\n"+ batch.getId() + "      " + barcode);
//                            }
//                        }
//                    }
                }
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        } finally {
            CaptureHome.close();
            DiskHome.close();
        }
    }

    public static boolean isLong(String str) {
        try {
            long number = Long.parseLong(str);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea output;
    private javax.swing.JLabel repName;
    // End of variables declaration//GEN-END:variables
}
