 package com.gdit.capture.entity;
// Generated 13/10/2010 04:34:03 � by Hibernate Tools 3.2.0.beta7


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable , Comparable<Category> {

    // Fields    

     private long id;
     private Rep rep;
     private String name;
     private Boolean dflt;
     private boolean createFolder;
     private Set captures = new HashSet(0);
     private Set rolesCategorieses = new HashSet(0);
     private Set fieldCategorieses = new HashSet(0);
     // Constructors

    /** default constructor */
    public Category() {
    }

	/** minimal constructor */
    public Category(long id) {
        this.id = id;
    }
    /** full constructor */
    public Category(long id, Rep rep, String name, Set captures) {
       this.id = id;
       this.rep = rep;
       this.name = name;
       this.captures = captures;
    }
   
    // Property accessors
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Rep getRep() {
        return this.rep;
    }
    
    public void setRep(Rep rep) {
        this.rep = rep;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public boolean isCreateFolder() {
        return createFolder;
    }

    public void setCreateFolder(boolean createFolder) {
        this.createFolder = createFolder;
    }
    
    
    
    public Set getCaptures() {
        return this.captures;
    }
    
    public void setCaptures(Set captures) {
        this.captures = captures;
    }

    public Set getFieldCategorieses() {
        return fieldCategorieses;
    }

    public void setFieldCategorieses(Set fieldCategorieses) {
        this.fieldCategorieses = fieldCategorieses;
    }

    public Set getRolesCategorieses() {
        return rolesCategorieses;
    }

    public void setRolesCategorieses(Set rolesCategorieses) {
        this.rolesCategorieses = rolesCategorieses;
    }

    public Boolean getDflt() {
        return dflt;
    }

    public void setDflt(Boolean dflt) {
        this.dflt = dflt;
    }

    

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Category other = (Category) obj;
        if (this.id != other.id) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 11 * hash + (int) (this.id ^ (this.id >>> 32));
        return hash;
    }



    @Override
    public int compareTo(Category o) {
        return new Long(this.getId()).compareTo(o.getId());
    }

    @Override
    public String toString() {
        return this.getName();
    }

}


