package com.gdit.capture.entity;
// Generated 23/10/2010 01:01:59 � by Hibernate Tools 3.2.0.beta7


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Groups generated by hbm2java
 */
public class Groups  implements java.io.Serializable {

    // Fields    

     private int id;
     private String groupName;
     private Set rolesGroupses = new HashSet(0);
     private Set usersGroupses = new HashSet(0);

     // Constructors

    /** default constructor */
    public Groups() {
    }

	/** minimal constructor */
    public Groups(int id) {
        this.id = id;
    }
    /** full constructor */
    public Groups(int id, String groupName, Set rolesGroupses, Set usersGroupses) {
       this.id = id;
       this.groupName = groupName;
       this.rolesGroupses = rolesGroupses;
       this.usersGroupses = usersGroupses;
    }
   
    // Property accessors
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
    public Set getRolesGroupses() {
        return this.rolesGroupses;
    }
    
    public void setRolesGroupses(Set rolesGroupses) {
        this.rolesGroupses = rolesGroupses;
    }
    public Set getUsersGroupses() {
        return this.usersGroupses;
    }
    
    public void setUsersGroupses(Set usersGroupses) {
        this.usersGroupses = usersGroupses;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Groups other = (Groups) obj;
        if (this.id != other.id) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 37 * hash + this.id;
        return hash;
    }




}


