package com.gdit.capture.entity;
// Generated 27/10/2010 06:02:39 � by Hibernate Tools 3.2.0.beta7



/**
 * ModulesRoles generated by hbm2java
 */
public class ModulesRoles  implements java.io.Serializable {

    // Fields    

     private ModulesRolesId id;
     private Roles roles;
     private Modules modules;

     // Constructors

    /** default constructor */
    public ModulesRoles() {
        id = new ModulesRolesId();
    }

    /** full constructor */
    public ModulesRoles(ModulesRolesId id, Roles roles, Modules modules) {
       this.id = id;
       this.roles = roles;
       this.modules = modules;
    }
   
    // Property accessors
    public ModulesRolesId getId() {
        return this.id;
    }
    
    public void setId(ModulesRolesId id) {
        this.id = id;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        id.setRoleId(roles.getId());
        this.roles = roles;
    }
    public Modules getModules() {
        return this.modules;
    }
    
    public void setModules(Modules modules) {
        id.setModuleId(modules.getId());
        this.modules = modules;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final ModulesRoles other = (ModulesRoles) obj;
        if (this.id != other.id && (this.id == null || !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 37 * hash + (this.id != null ? this.id.hashCode() : 0);
        return hash;
    }

 


}


