package com.gdit.capture.entity;
// Generated 15/12/2010 08:54:04   by Hibernate Tools 3.2.0.beta7



/**
 * NsecHejraToGregorian generated by hbm2java
 */
public class NsecHejraToGregorian  implements java.io.Serializable {

    // Fields    

     private NsecHejraToGregorianId id;

     // Constructors

    /** default constructor */
    public NsecHejraToGregorian() {
    }

    /** full constructor */
    public NsecHejraToGregorian(NsecHejraToGregorianId id) {
       this.id = id;
    }
   
    // Property accessors
    public NsecHejraToGregorianId getId() {
        return this.id;
    }
    
    public void setId(NsecHejraToGregorianId id) {
        this.id = id;
    }




}


