package com.gdit.capture.entity;
// Generated 14/12/2010 07:03:58 by Hibernate Tools 3.2.0.beta7

import java.util.Date;

/**
 * PatientsDoc generated by hbm2java
 */
public class PatientsDoc implements java.io.Serializable {

    // Fields    
    private long id;
    private Investigation investigation;
    private String docNo;
    private String investigationDate;
    private Boolean img;
    private Integer userId;
    private Date createdDate;
    // Constructors

    /** default constructor */
    public PatientsDoc() {
    }

    /** minimal constructor */
    public PatientsDoc(long id) {
        this.id = id;
    }

    /** full constructor */
    public PatientsDoc(long id, Investigation investigation, String docNo, String investigationDate) {
        this.id = id;
        this.investigation = investigation;
        this.docNo = docNo;
        this.investigationDate = investigationDate;
    }

    // Property accessors
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Investigation getInvestigation() {
        return this.investigation;
    }

    public void setInvestigation(Investigation investigation) {
        this.investigation = investigation;
    }

    public String getDocNo() {
        return this.docNo;
    }

    public void setDocNo(String docNo) {
        this.docNo = docNo;
    }

    public String getInvestigationDate() {
        return this.investigationDate;
    }

    public void setInvestigationDate(String investigationDate) {
        this.investigationDate = investigationDate;
    }

    public Boolean getImg() {
        return img;
    }

    public void setImg(Boolean img) {
        this.img = img;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Date getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final PatientsDoc other = (PatientsDoc) obj;
        if (this.id != other.id) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 53 * hash + (int) (this.id ^ (this.id >>> 32));
        return hash;
    }
}
