package com.gdit.capture.entity;
// Generated 05/01/2011 04:28:00  by Hibernate Tools 3.2.0.beta7


import java.math.BigDecimal;

/**
 * RolesCategoriesId generated by hbm2java
 */
public class RolesCategoriesId  implements java.io.Serializable {

    // Fields    

     private long roleId;
     private long categoryId;

     // Constructors

    /** default constructor */
    public RolesCategoriesId() {
    }

    /** full constructor */
    public RolesCategoriesId(long roleId, long categoryId) {
       this.roleId = roleId;
       this.categoryId = categoryId;
    }
   
    // Property accessors
    public long getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(long roleId) {
        this.roleId = roleId;
    }

    public long getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(long categoryId) {
        this.categoryId = categoryId;
    }

   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RolesCategoriesId) ) return false;
		 RolesCategoriesId castOther = ( RolesCategoriesId ) other;

		 return (this.getRoleId()==castOther.getRoleId())
 && (this.getCategoryId()==castOther.getCategoryId());
   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + (int) this.getRoleId();
         result = (int) (37 * result + this.getCategoryId());
         return result;
   }

    



}


