package com.gdit.capture.entity;
// Generated 23/10/2010 01:01:59  by Hibernate Tools 3.2.0.beta7



/**
 * RolesGroups generated by hbm2java
 */
public class RolesGroups  implements java.io.Serializable {

    // Fields    

     private RolesGroupsId id;
     private Roles roles;
     private Groups groups;

     // Constructors

    /** default constructor */
    public RolesGroups() {
      id = new RolesGroupsId();
    }

    /** full constructor */
    public RolesGroups(RolesGroupsId id, Roles roles, Groups groups) {
       this.id = id;
       this.roles = roles;
       this.groups = groups;
    }
   
    // Property accessors
    public RolesGroupsId getId() {

        return this.id;
    }
    
    public void setId(RolesGroupsId id) {

        this.id = id;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {

        id.setRolesId(roles.getId());
        this.roles = roles;
    }
    public Groups getGroups() {
      // id.setGroupId(groups.getId());
        return this.groups;
    }
    
    public void setGroups(Groups groups) {

         id.setGroupId(groups.getId());
        this.groups = groups;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final RolesGroups other = (RolesGroups) obj;
        if (this.id != other.id && (this.id == null || !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 67 * hash + (this.id != null ? this.id.hashCode() : 0);
        return hash;
    }




}


