package com.gdit.capture.entity;
 
import java.math.BigDecimal;

/**
 * UsersRolesId generated by hbm2java
 */
public class UsersRolesId  implements java.io.Serializable {

    // Fields    

     private BigDecimal userId;
     private BigDecimal roleId;

     // Constructors

    /** default constructor */
    public UsersRolesId() {
    }

    /** full constructor */
    public UsersRolesId(BigDecimal userId, BigDecimal roleId) {
       this.userId = userId;
       this.roleId = roleId;
    }
   
    // Property accessors
    public BigDecimal getUserId() {
        return this.userId;
    }
    
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }
    public BigDecimal getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(BigDecimal roleId) {
        this.roleId = roleId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsersRolesId) ) return false;
		 UsersRolesId castOther = ( UsersRolesId ) other; 
         
		 return ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) )
 && ( (this.getRoleId()==castOther.getRoleId()) || ( this.getRoleId()!=null && castOther.getRoleId()!=null && this.getRoleId().equals(castOther.getRoleId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
         result = 37 * result + ( getRoleId() == null ? 0 : this.getRoleId().hashCode() );
         return result;
   }   


}


