package com.gdit.capture.entity;
 

/**
 * UsersRoles generated by hbm2java
 */
public class UsersRoles  implements java.io.Serializable {

    // Fields    

     private UsersRolesId id;
     private Roles roles;
     private Users users;

     // Constructors

    /** default constructor */
    public UsersRoles() {
    }

    /** full constructor */
    public UsersRoles(UsersRolesId id, Roles roles, Users users) {
       this.id = id;
       this.roles = roles;
       this.users = users;
    }
   
    // Property accessors
    public UsersRolesId getId() {
        return this.id;
    }
    
    public void setId(UsersRolesId id) {
        this.id = id;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final UsersRoles other = (UsersRoles) obj;
        if (this.id != other.id && (this.id == null || !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 83 * hash + (this.id != null ? this.id.hashCode() : 0);
        return hash;
    }


     

}


