package com.gdit.capture.entity;
// Generated 23/10/2010 01:01:59  by Hibernate Tools 3.2.0.beta7



/**
 * UsersGroups generated by hbm2java
 */
public class UsersGroups  implements java.io.Serializable {

    // Fields    

     private UsersGroupsId id;
     private Users users;
     private Groups groups;

     // Constructors

    /** default constructor */
    public UsersGroups() {
        id = new UsersGroupsId();
    }

    /** full constructor */
    public UsersGroups(UsersGroupsId id, Users users, Groups groups) {
       this.id = id;
       this.users = users;
       this.groups = groups;
    }
   
    // Property accessors
    public UsersGroupsId getId() {
        return this.id;
    }
    
    public void setId(UsersGroupsId id) {

        this.id = id;
    }
    public Users getUsers() {

        return this.users;
    }
    
    public void setUsers(Users users) {
        id.setUserId(users.getId());
        this.users = users;
    }
    public Groups getGroups() {

        return this.groups;
    }
    
    public void setGroups(Groups groups) {
        id.setGroupId(groups.getId());
        this.groups = groups;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final UsersGroups other = (UsersGroups) obj;
        if (this.id != other.id && (this.id == null || !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 79 * hash + (this.id != null ? this.id.hashCode() : 0);
        return hash;
    }




}


