package com.gdit.capture.entity;
// Generated 23/10/2010 01:01:59 � by Hibernate Tools 3.2.0.beta7


import java.math.BigDecimal;

/**
 * UsersGroupsId generated by hbm2java
 */
public class UsersGroupsId  implements java.io.Serializable {

    // Fields    

     private Integer userId;
     private Integer groupId;

     // Constructors

    /** default constructor */
    public UsersGroupsId() {

    }

    /** full constructor */
    public UsersGroupsId(int userId, int groupId) {
       this.userId = userId;
       this.groupId = groupId;
    }
   
    // Property accessors
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public Integer getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsersGroupsId) ) return false;
		 UsersGroupsId castOther = ( UsersGroupsId ) other; 
         
		 return ( (this.getUserId()==getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) )
 && ( (this.getGroupId()==castOther.getGroupId()) || ( this.getGroupId()!=null && castOther.getGroupId()!=null && this.getGroupId().equals(castOther.getGroupId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
         result = 37 * result + ( getGroupId() == null ? 0 : this.getGroupId().hashCode() );
         return result;
   }   


}


