/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CategoriesDlg.java
 *
 * Created on 10/01/2011, 03:51:51 م
 */
package com.gdit.capture.gui;

import com.gdit.capture.entity.Category;
import com.gdit.capture.entity.GeneralHome;
import com.gdit.capture.entity.Rep;
import com.gdit.capture.entity.Users;
import com.gdit.capture.run.CaptureMain;
import com.gdit.capture.run.QAMain;
import com.gdit.capture.run.ScanExceptionMain;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ResourceBundle;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Bahi
 */
public class CategoriesDlg extends javax.swing.JDialog {

    private Rep rep;
    private DefaultComboBoxModel categoriesModel;
    private ResourceBundle bundle;
    private Users user;
    private JFrame parent;

    /** Creates new form CategoriesDlg */
    public CategoriesDlg(JFrame parent, boolean modal, Rep rep, Users user, ResourceBundle bundle) {
        super(parent, modal);
        this.bundle = bundle;
        this.user = user;
        this.parent = parent;
        this.rep = rep;
        initComponents();
        this.centerScreen();
        init();
    }

    private void init() {
        GeneralHome dao = new GeneralHome();
        Set<Category> categories = (Set<Category>) rep.getCategories();
        categoriesModel = new DefaultComboBoxModel(categories.toArray());
        categoriesCombo.setModel(categoriesModel);
        Category category = (Category) categoriesModel.getSelectedItem();
        boolean catAuth = dao.authnticateUserCategory(user, category);
        if (!catAuth) {
            JOptionPane.showMessageDialog(this, bundle.getString("category.not.auth"));

        }
        return;

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categoriesCombo = new javax.swing.JComboBox();
        selectButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        categoriesCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/gdit/bundle/capture"); // NOI18N
        selectButton.setText(bundle.getString("select")); // NOI18N
        selectButton.setActionCommand(bundle.getString("select")); // NOI18N
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonActionPerformed(evt);
            }
        });

        jLabel1.setText(bundle.getString("categories")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(categoriesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(selectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoriesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addComponent(selectButton)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonActionPerformed
        // TODO add your handling code here:
        Category category = (Category) categoriesCombo.getSelectedItem();
        this.dispose();
        if(category!=null)
        if(parent instanceof CaptureMain)
            ((CaptureMain)parent).changeCategory(category);
        else if(parent instanceof QAMain)
            ((QAMain) parent).changeCategory(category);
        else if(parent instanceof ScanExceptionMain)
            ((ScanExceptionMain)parent).changeCategory(category);
    }//GEN-LAST:event_selectButtonActionPerformed

    private void centerScreen() {
        setTitle("");
        addWindowListener(new WindowAdapter() {

            public void windowClosing(WindowEvent e) {

                //System.exit(0);
            }
        });
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension screenSize = tk.getScreenSize();
        int screenHeight = screenSize.height / 2;
        int screenWidth = screenSize.width / 2;
        //setSize(screenWidth, screenHeight - 20);
        setLocation(screenWidth - this.getWidth() / 2, screenHeight - this.getHeight() / 2);

    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) { 
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox categoriesCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton selectButton;
    // End of variables declaration//GEN-END:variables
}
