/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UsersPanel.java
 *
 * Created on 18/01/2011, 02:51:18 م
 */
package com.gdit.capture.gui;

import com.gdit.capture.entity.Users;
import com.gdit.capture.entity.UsersHome;
import com.gdit.capture.model.ButtonEditor;
import com.gdit.capture.model.ButtonRenderer;
import com.gdit.capture.model.rep.RepButtonRenderer;
import com.gdit.capture.model.user.UserButtonEditor;
import com.gdit.capture.model.user.UserButtonRenderer;
import com.gdit.capture.model.user.UsersTableModel;
import com.jidesoft.swing.JideSwingUtilities;
import java.awt.Component;
import java.awt.ComponentOrientation;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author Bahi
 */
public class UsersPanel extends javax.swing.JPanel {

    /** Creates new form UsersPanel */
    /** Creates new form NewJDialog */
    public UsersPanel() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e1) {
            e1.printStackTrace();
        }
        if (locale == null) {
            locale = new Locale("ar");
        }
        bundle = ResourceBundle.getBundle("com/gdit/bundle/capture");
        initComponents();
        init();
        changeScreenDirection(this, locale);
    }

    private void init() {
        try {
            UsersHome usersDao = new UsersHome();
            users = usersDao.getAllUsers();
            usersModel = new UsersTableModel(usersTable, users, bundle);
            usersTable.setModel(usersModel);
            usersTable.getColumn(bundle.getString("edit")).setCellRenderer(new UserButtonRenderer());
            usersTable.getColumn(bundle.getString("delete")).setCellRenderer(new UserButtonRenderer());
            usersTable.getColumn(bundle.getString("groups")).setCellEditor(new UserButtonEditor(this, new JCheckBox(), bundle));
            usersTable.getColumn(bundle.getString("edit")).setCellEditor(new UserButtonEditor(this, new JCheckBox(), bundle));
            usersTable.getColumn(bundle.getString("delete")).setCellEditor(new UserButtonEditor(this, new JCheckBox(), bundle));
            usersTable.getColumn(bundle.getString("groups")).setCellEditor(new UserButtonEditor(this, new JCheckBox(), bundle));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    public void edit(Users user) {
        try {
            txtUserName.setText(user.getUserName());
            chkActive.setSelected(user.getActive());
            addButton.setText(bundle.getString("edit"));
            addButton.setActionCommand(bundle.getString("edit"));
            this.user = user;
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    public static void changeScreenDirection(Component screen, Locale locale) {
        try {
            if (locale == null) {
                locale = new Locale("ar");

            }
            if (ComponentOrientation.getOrientation(locale).equals(ComponentOrientation.RIGHT_TO_LEFT)) {
                JideSwingUtilities.toggleRTLnLTR(screen);
                JideSwingUtilities.invalidateRecursively(screen);
                SwingUtilities.updateComponentTreeUI(screen);

            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    public void clear() {
        txtPassword.setText("");
        txtRePassword.setText("");
        txtUserName.setText("");
        chkActive.setSelected(false);
    }

    public JFrame getFrame() {
        return frame;
    }

    public void setFrame(JFrame frame) {
        this.frame = frame;
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUserName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        chkActive = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtRePassword = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JPasswordField();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/gdit/bundle/capture"); // NOI18N
        jLabel1.setText(bundle.getString("username")); // NOI18N

        jLabel2.setText(bundle.getString("password")); // NOI18N

        jLabel3.setText(bundle.getString("repassword")); // NOI18N

        jLabel4.setText(bundle.getString("active")); // NOI18N

        addButton.setText(bundle.getString("add")); // NOI18N
        addButton.setActionCommand(bundle.getString("add")); // NOI18N
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jButton2.setText(bundle.getString("cancel")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(usersTable);

        jLabel5.setText(bundle.getString("users")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addComponent(chkActive)
                            .addComponent(txtUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                            .addComponent(txtRePassword, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(chkActive))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        if (evt.getActionCommand().equals(bundle.getString("add"))) {
            addUser();
        } else if (evt.getActionCommand().equals(bundle.getString("edit"))) {
            updateUser();
        }
}//GEN-LAST:event_addButtonActionPerformed

    private void addUser() {
        try {
            if (validateUser()) {
                Users user = new Users();
                UsersHome dao = new UsersHome();
                user.setPassword(txtPassword.getText());
                user.setUserName(txtUserName.getText());
                user.setActive(chkActive.isSelected());
                dao.persist(user);
                dao.commit();
                UsersHome.close();
                usersModel.addRow(user);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        // users.add(user);
        clear();

    }

    private void updateUser() {
        try {
            if (validateUser()) {
                
                UsersHome dao = new UsersHome();
                user.setPassword(txtPassword.getText());
                user.setUserName(txtUserName.getText());
                user.setActive(chkActive.isSelected());
                dao.attachDirty(user);
                dao.commit();
                UsersHome.close();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        // users.add(user);
        clear();

    }

    private boolean validateUser() {
        if (txtUserName.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, bundle.getString("error.username.required"));
            return false;
        } else if (txtPassword.getText().trim().equals("") || txtRePassword.getText().equals("")) {
            JOptionPane.showMessageDialog(this, bundle.getString("error.password.required"));
            return false;
        } else if (!txtPassword.getText().equals(txtRePassword.getText())) {
            JOptionPane.showMessageDialog(this, bundle.getString("error.password.identical"));
            return false;
        }
        return true;
    }

    private JFrame frame;
    private List<Users> users;
    private UsersTableModel usersModel;
    private ResourceBundle bundle;
    private Locale locale;
    private Users user;

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        clear();
        addButton.setText(bundle.getString("add"));
        addButton.setActionCommand(bundle.getString("add"));
}//GEN-LAST:event_jButton2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JCheckBox chkActive;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtRePassword;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTable usersTable;
    // End of variables declaration//GEN-END:variables
}
